variables:
  DOCKER_DRIVER: overlay2

image: maven:3.3-jdk-8

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - mvn checkstyle:checkstyle

deployToAWS:
  only:
    - master
    - developer
  stage: deploy
  script:
    - bash deploy.sh
